"""Add Upvote and Comment

Revision ID: 1e412623b61f
Revises: b52c3a6ed212
Create Date: 2025-05-04 13:57:10.072708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e412623b61f'
down_revision = 'b52c3a6ed212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('upvotes', schema=None) as batch_op:
        batch_op.drop_constraint('one_upvote_per_user', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upvotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.create_unique_constraint('one_upvote_per_user', ['user_id', 'artwork_id'])

    with op.batch_alter_table('artwork', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
